# Самостоятельная работа № 1

Всего баллов: 11

Максимальный балл за работу: 10

Будем работать с датасетом Pima Indian Diabetes - это набор данных из Национального института диабета, болезней органов пищеварения и почек. Целью набора данных является диагностическое прогнозирование наличия диабета у пациента. Несколько ограничений были наложены на выбор этих экземпляров из большой базы данных. В частности, все пациенты здесь - женщины в возрасте от 21 года, индийского происхождения.

In [1]:
import pandas as pd
data = pd.read_csv('https://raw.githubusercontent.com/rogovich/Data/master/data/pima-indians-diabetes.csv')
data.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
5,5,116.0,74.0,NaN,NaN,25.6,0.201,30,0
6,3,78.0,50.0,32.0,88.0,31.0,0.248,26,1
7,10,115.0,NaN,NaN,NaN,35.3,0.134,29,0
8,2,197.0,70.0,45.0,543.0,30.5,0.158,53,1
9,8,125.0,96.0,NaN,NaN,NaN,0.232,54,1

Описание данных:

* **Pregnancies** - данная единица отображает количество беременностей, единицы измерения - целые числа от 0 до N. Тип переменной - количественная, дискретная.
* **Glucose** - данная единица отображает уровень глюкозы в крови, единицы измерения - целые числа. Тип переменной - количественная, дискретная.
* **BloodPressure** - данная единица отображает артериальное давление, единицы измерения - миллиметры р/с, целые числа. Тип переменной - количественная, дискретная.
* **SkinThickness** - данная единица отображает обхват трицепса в миллиметрах, целые числа. Тип переменной - количественная, дискретная.
* **Insulin** - данная единица отображает уровень инсулина в крови, целые числа. Тип переменной - количественная, дискретная.
* **BMI** - данная единица отображает индекс массы тела. Тип переменной - количественная, непрерывная.
* **DiabetesPedigreeFunction** - данная единица отображает риск наследственного диабета в зависимости наличия диабета у родственников. Выражается десятичной дробью от 0 до 1. Тип переменной - количественная, непрерывная.
* **Age** - данная единица отражает возраст в целых числах. Тип переменной - количественная, дискретная.
* **Class** - данная единица отражает наличие диабета у субъекта, выражена 0(здоров) или 1(болен). Тип переменной - категориальная, бинарная.

## Задание 1 (фильтрация) 
*1 балл*

У скольких женщин старше 50 лет обнаружен диабет?

In [2]:
# ваш код здесь
data[(data['Age'] > 50) & (data['Class'] == 1)].shape

(38, 9)

## Задание 2 (фильтрация)
*1 балл*

Сколько пропущенных значений в колонке `Insulin`? Вы должны именно отфильтровать соответствующие ряды и вывести их количество.

In [6]:
# ваш код здесь
data[data['Insulin'].isna()].shape

(374, 9)

## Задание 3 (фильтрация) 
*1 балл*

Сколько женщин успели родить 3 или более детей до 30 лет?

In [8]:
# ваш код здесь
data[(data['Age'] <30) & (data['Pregnancies'] >= 3)].shape

(117, 9)

## Задание 4 (фильтрация) 

*2 балла*

Нормальным кровяным давлением будем считать давление в диапазоне [80-89] (включительно). У какого процента женщин давление нормальное?

In [11]:
# ваш код здесь
len(data[(data['BloodPressure'] >= 80) & (data['BloodPressure'] <= 89)])/len(data['BloodPressure']) * 100

18.880208333333336

## Задание 5 (создание переменных)

*1 балл*

Добавьте новый бинарный признак:

**wasPregnant**  {0,1} - была женщина беременна (1) или нет (0)

In [14]:
# ваш код здесь
import numpy as np
data['wasPregnant'] = np.where(data['Pregnancies'] >= 1, 1, 0)
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Class,wasPregnant
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0,1
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0,1
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1,0
...,...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63,0,1
764,2,122.0,70.0,27.0,NaN,36.8,0.340,27,0,1
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30,0,1
766,1,126.0,60.0,NaN,NaN,30.1,0.349,47,1,1
767,1,93.0,70.0,31.0,NaN,30.4,0.315,23,0,1

## Задание 6 (фильтрация)

*2.5 балла*

Сравните проценты больных диабетом среди женщин, которые были беременны и не были.
Выведите `True`, если среди тех, у кого были беременности, процент больных диабетом выше и `False` в другом случае.

In [21]:
# ваш код здесь
dino = data[(data['Class'] == 1) & (data['Pregnancies'] == 0)]
diye = data[(data['Class'] == 1) & (data['Pregnancies'] > 0)]
nono = data[(data['Class'] == 0) & (data['Pregnancies'] == 0)]
noye = data[(data['Class'] == 0) & (data['Pregnancies'] > 0)]

## Задание 7 (создание новых переменных)

*2.5 балла*

Добавьте новый категориальный признак **bodyType** на основе столбца `BMI`:

BMI Categories:

* Underweight = <18.5

* Normal weight = 18.5–24.9

* Overweight = 25–29.9

* Obesity = BMI of 30 or greater

Признак должен принимать значения **Underweight**, **Normal weight**, **Overweight** и **Obesity**.

In [17]:
# ваш код здесь
def get_type(blood):
    if blood <18.5:
        return 'Underweight'
    elif blood <24.9:
        return 'Normal weight'
    elif blood <29.9:
        return 'Normal weight'
    elif blood >= 30:
        return 'Obesity'
    else:
        return blood

In [18]:
data['bodyType'] = data['BMI'].apply(get_type)
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Class,wasPregnant,bodyType
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1,1,Obesity
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0,1,Normal weight
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1,1,Normal weight
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0,1,Normal weight
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1,0,Obesity
...,...,...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63,0,1,Obesity
764,2,122.0,70.0,27.0,NaN,36.8,0.340,27,0,1,Obesity
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30,0,1,Normal weight
766,1,126.0,60.0,NaN,NaN,30.1,0.349,47,1,1,Obesity
767,1,93.0,70.0,31.0,NaN,30.4,0.315,23,0,1,Obesity